### ISSUE TITLE
macOS directory not working

### ISSUE THREAD

**Issue by gabrielegasponi** [dsdanielko/cura-ringing-tower-script#2]
Unable to find specified directory. However, the specified folder is located at /Applications/Ultimaker-Cura.app/Contents/Resources/share/cura/plugins/PostProcessingPlugin, but I can't find the Input shaping option in the cura post processing menu if I drop the file in this folder. (cura 5.2.1, macOS 13.2.1)

**Comment by dsdanielko** [comment]
Ok you're going to have to help me here, I do not have a mac installation and I don't actually know where it would go. I was told that that directory should work, but it seems that in the last couple of cura versions the script system was changed. Could you try and find where the script is meant to be placed for me? I found this to help https://community.ultimaker.com/topic/43278-installing-post-process-script-on-macos/

**Comment by gabrielegasponi** [comment]
Yes, the scripts should be placed at /Applications/Ultimaker-Cura.app/Contents/Resources/share/cura/plugins/PostProcessingPlugin/scripts. I found all the .py scripts of the plug-in in that folder, but coping the new script doesn’t result in the new script showing up in the list inside cura, I don’t know why

**Comment by dsdanielko** [comment]
Can you try this please:

"A "PostProcessingPlugin" is a script that runs after slicing has finished.  They alter the gcode rather than providing pre-slice options.  They are often (unless I write them) fairly simple Python scripts and indeed go in the **"Scripts" folder in the Cura installation folder or in the "Scripts" folder in your "configuration folder"**."

So not in the plugins/PostProcessingPlugin/scripts folder, try somewhere close to the base directory. Is there a configurations folder you can find?

**Comment by jeroen85** [comment]
Got it working by placing it in
`/Users/<Username>/Library/Application Support/cura/5.3/scripts`

**Comment by dsdanielko** [comment]
Fantastic, thanks
